CREATE TYPE transaction_status AS ENUM ('success', 'failure', 'pending');
CREATE TYPE transaction_type AS ENUM ('top_up', 'purchase');

DROP TABLE IF EXISTS Users CASCADE;
CREATE TABLE IF NOT EXISTS Users (
user_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
username varchar(40) NOT NULL
);

DROP TABLE IF EXISTS Balance;
CREATE TABLE IF NOT EXISTS Balance (
balance_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id integer NOT NULL,
balance decimal DEFAULT 0,
FOREIGN KEY (user_id) REFERENCES Users (user_id)
);

DROP TABLE IF EXISTS Transactions;
CREATE TABLE IF NOT EXISTS Transactions (
transaction_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
user_id integer NOT NULL,
amount numeric DEFAULT 0,
status transaction_status NOT NULL,
type transaction_type NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
FOREIGN KEY (user_id) REFERENCES Users (user_id)
);


INSERT INTO Users (username)
VALUES ('Kate'),
       ('Bob'),
       ('Tom');

INSERT INTO Balance (user_id, balance)
VALUES ((SELECT user_id FROM Users WHERE username='Kate'), 5000),
       ((SELECT user_id FROM Users WHERE username='Bob'), 1500),
       ((SELECT user_id FROM Users WHERE username='Tom'), 100);
